# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
  # Docs at https://docs.vagrantup.com.

  config.vm.box = "dot-iris-base"

  config.vm.provider "virtualbox" do |vb|
    vb.name = "dotIrisVm"
    # Display the VirtualBox GUI when booting the machine
    # vb.gui = true

    # Attach Guest Additions image. Doesn't work without using `emptydrive` first.
    # vb.customize ["storageattach", :id, "--storagectl", "IDE Controller", "--type", "dvddrive", "--port", "0", "--device", "0", "--medium", "additions"]
  end

  config.vm.provision "shell", privileged: false, path: "./user-build.sh"
end
