# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
  # The most common configuration options are documented and commented below.
  # For a complete reference, please see the online documentation at
  # https://docs.vagrantup.com.

  config.vm.box = "dot-iris-base"

  # Share an additional folder to the guest VM. The first argument is
  # the path on the host to the actual folder. The second argument is
  # the path on the guest to mount the folder. And the optional third
  # argument is a set of non-required options.
  # config.vm.synced_folder "../data", "/vagrant_data"

  config.vm.provider "virtualbox" do |vb|
    vb.name = "dotIrisVm"
    # Display the VirtualBox GUI when booting the machine
    # vb.gui = true

    # Attach Guest Additions image. Doesn't work without using `emptydrive` first.
    # vb.customize ["storageattach", :id, "--storagectl", "IDE Controller", "--type", "dvddrive", "--port", "0", "--device", "0", "--medium", "additions"]
  end

  config.vm.provision "shell", privileged: false, path: "./user-build.sh"
end
