version: 2
updates:
- package-ecosystem: bundler
  directory: "/website"
  schedule:
    interval: monthly
  # Disable non-security version updates
  open-pull-requests-limit: 0
  versioning-strategy: increase-if-necessary
