dist: bionic
language: minimal

services:
  - docker

env:
  global:
  - NJOBS="2"
  - CONTRIB_NAME="dot-iris"
  - OPAM_NAME="dot-iris-builddep"
  matrix:
  # TODO: remove unneeded versions below
  - COQ_IMAGE="coqorg/coq:8.10"
  # - COQ_IMAGE="coqorg/coq:8.11"
  # - COQ_IMAGE="coqorg/coq:dev"
  # "default" switch: $COMPILER
  # this config uses: $COMPILER_EDGE (cf. "opam switch" command below)
  # See https://github.com/coq-community/docker-coq/wiki#supported-tags

before_script:
  export -f travis_fold
  export -f travis_time_start
  export -f travis_time_finish

install: |
  # Download the COQ container
  docker pull ${COQ_IMAGE}
  # Start the COQ container
  docker run -d -i --init --name=COQ -v ${TRAVIS_BUILD_DIR}:/home/coq/${CONTRIB_NAME} -w /home/coq/${CONTRIB_NAME} ${COQ_IMAGE}
  # Prepare the COQ container
  docker exec COQ /bin/bash --login -c "
    export PS4='+ \e[33;1m(\$0 @ line \$LINENO) \$\e[0m '; set -ex
    if [ -n \"\${COMPILER_EDGE}\" ]; then opam switch \${COMPILER_EDGE}; eval \$(opam env); fi
    echo -en 'travis_fold:start:update\\r'
    travis_time_start
    opam repo add iris-dev https://gitlab.mpi-sws.org/FP/opam-dev.git --set-default --all
    opam update -y
    opam pin add -y -n -k path $OPAM_NAME .
    travis_time_finish
    echo -en 'travis_fold:end:update\\r'
    #
    echo -en 'travis_fold:start:autosubst\\r'
    travis_time_start
    opam install -y -v -j ${NJOBS} coq-autosubst
    travis_time_finish
    echo -en 'travis_fold:end:autosubst\\r'
    #
    echo -en 'travis_fold:start:iris\\r'
    travis_time_start
    opam install -y -v -j ${NJOBS} --deps-only $OPAM_NAME
    travis_time_finish
    echo -en 'travis_fold:end:iris\\r'
    #
    opam config list; opam repo list; opam list
    " install

script:
- echo -e "${ANSI_YELLOW}Building ${CONTRIB_NAME}...${ANSI_RESET}" && travis_fold start "script"
- |
  docker exec COQ /bin/bash --login -c "
    export PS4='+ \e[33;1m(\$0 @ line \$LINENO) \$\e[0m '; set -ex
    sudo chown -R coq:coq /home/coq/${CONTRIB_NAME}
    ( make -j ${NJOBS} TIMED=1 )
    " script
- travis_fold end "script"

after_script:
- docker stop COQ  # optional but recommended
