dist: bionic
language: minimal

services:
  - docker

env:
  global:
  - NJOBS="2"
  - CONTRIB_NAME="dot-iris"
  - OPAM_NAME="dot-iris-builddep"
  matrix:
  - COQ_IMAGE="blaisorblade/docker-dot-iris:2020-01-21.1.676a5302"
  - COQ_IMAGE="blaisorblade/docker-dot-iris:coq-8.11-dev-iris-2020-01-21.1.676a5302"
  # this config uses: $COMPILER_EDGE (cf. "opam switch" command below)
  # See https://github.com/coq-community/docker-coq/wiki#supported-tags

before_install: |
  export -f travis_fold
  export -f travis_time_start
  export -f travis_time_finish
  do_travis() {
    travis_fold start "$1"
    travis_time_start
    docker exec COQ /bin/bash --login -c "
      export PS4='+ \e[33;1m(\$0 @ line \$LINENO) \$\e[0m '; set -ex
      $2" "$1"
    ret=$?
    travis_time_finish
    travis_fold end "$1"
    return $ret
  }
  export -f do_travis

install: |
  # Download the COQ container
  docker pull ${COQ_IMAGE}
  # Start the COQ container
  docker run -d -i --init --name=COQ -v ${TRAVIS_BUILD_DIR}:/home/coq/${CONTRIB_NAME} -w /home/coq/${CONTRIB_NAME} ${COQ_IMAGE}
  # Prepare the COQ container
  do_travis "update" "
    if [ -n \"\${COMPILER_EDGE}\" ]; then opam switch \${COMPILER_EDGE}; eval \$(opam env); fi
    opam update -y
    opam pin add -y -n -k path $OPAM_NAME ."
  #
  # Likely redundant, except during upgrades
  do_travis "deps" "opam install -y -v -j ${NJOBS} --deps-only $OPAM_NAME"
  do_travis "settings" "opam config list; opam repo list; opam list"

script:
- echo -e "${ANSI_YELLOW}Building ${CONTRIB_NAME}...${ANSI_RESET}"
- |
  do_travis "script" "
    sudo chown -R coq:coq /home/coq/${CONTRIB_NAME}
    ( make -k -j ${NJOBS} TIMED=1 )"

after_script:
- docker stop COQ  # optional but recommended
