# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
  # The most common configuration options are documented and commented below.
  # For a complete reference, please see the online documentation at
  # https://docs.vagrantup.com.

  config.vm.box = "bento/ubuntu-20.04"

  # Disable automatic box update checking. If you disable this, then
  # boxes will only be checked for updates when the user runs
  # `vagrant box outdated`. This is not recommended.
  # config.vm.box_check_update = false

  # Provider-specific configuration so you can fine-tune various
  # backing providers for Vagrant. These expose provider-specific options.
  config.vm.provider "virtualbox" do |vb|
    vb.name = "dotIrisVmBase"
    # Display the VirtualBox GUI when booting the machine
    # vb.gui = true

    # Customize the amount of memory on the VM:
    vb.memory = "2048"
    vb.customize ["modifyvm", :id, "--graphicscontroller", "vmsvga", "--vram", "128"]
    vb.customize ["modifyvm", :id, "--accelerate3d", "off"]
    # Create drive
    vb.customize ["storageattach", :id, "--storagectl", "IDE Controller", "--type", "dvddrive", "--port", "0", "--device", "0", "--medium", "emptydrive"]
    # Attach Guest Additions image. Doesn't work without using `emptydrive` first.
    # vb.customize ["storageattach", :id, "--storagectl", "IDE Controller", "--type", "dvddrive", "--port", "0", "--device", "0", "--medium", "additions"]
  end

  config.vm.provision "shell", path: "./root-provision.sh"
  config.vm.provision "shell", privileged: false, path: "./user-provision.sh"
  # Restore baseline insecure key. To keep it, shut down the machine from
  # VirtualBox, not Vagrant.
  config.vm.provision "shell", privileged: false, inline: <<-SHELL
    curl -s https://raw.githubusercontent.com/hashicorp/vagrant/master/keys/vagrant.pub > ~/.ssh/authorized_keys
    chown vagrant.vagrant -R ~/.ssh
    chmod 0700 ~/.ssh
    chmod 0600 ~/.ssh/authorized_keys
  SHELL
end
